name: Sync main to public repo

on:
  push:
    branches:
      - main

jobs:
  push-to-public-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # 最新のコミット履歴のみを取得し、過去の履歴は含めない
          persist-credentials: false

      - name: Export snapshot from private repo
        run: |
          set -eu

          # エクスポート先の作業ツリーを作成（カレントディレクトリから直接rsyncだとpublishが再帰になるため）
          rm -rf export
          rsync -a --delete --exclude '.git' ./ ./export/

      - name: Append snapshot commit to public repo
        env:
          TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}
        run: |
          set -eu

          # 公開リポジトリをshallow clone
          git clone --depth 1 "https://ibuki-sakuma:${TARGET_REPO_PAT}@github.com/ibuki-sakuma/broaden-link.git" publish

          # エクスポートした内容で作業ツリーを置き換え（.git は消さないよう除外）
          rsync -a --delete --exclude '.git' ./export/ ./publish/

          cd publish

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A

          # 変更がなければスキップ
          if git diff --cached --quiet; then
            echo "No changes to publish"
            exit 0
          fi

          git commit -m "Publish snapshot from commit ${GITHUB_SHA:0:7}..."
          git push origin HEAD:main